<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS - Connection in each test case</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>265296c4-72db-48fc-9125-26f17486a3dd</testSuiteGuid>
   <testCaseLink>
      <guid>6aefbdc4-9e3d-4a3d-b087-51b2f8faa451</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Connection in each test case/SC - Verify initial count employee is equal to original</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>ca58c762-35d1-4587-a756-bb43ae2e2424</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Connection in each test case/Verify initial count employee is equal to original</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>ca58c762-35d1-4587-a756-bb43ae2e2424</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>originalEmployeeCount</value>
         <variableId>939266ee-5ca9-4578-a8e1-672ca09ee265</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>32b66af8-32c8-40bd-8f2d-8d19902870e6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>0</defaultValue>
         <description></description>
         <id>5e8c1193-be69-40da-bd10-b4d0756c1c80</id>
         <masked>false</masked>
         <name>empNo</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/Connection in each test case/SC - Verify insert is adding employee</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>748738a8-3d43-4b52-bfcb-03fc25de23d9</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Connection in each test case/Verify insert is adding employee</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>748738a8-3d43-4b52-bfcb-03fc25de23d9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>emp_no</value>
         <variableId>5e8c1193-be69-40da-bd10-b4d0756c1c80</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>748738a8-3d43-4b52-bfcb-03fc25de23d9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>birth_date</value>
         <variableId>1f93fea5-0292-4b5a-bc56-f3f418fa1eaa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>748738a8-3d43-4b52-bfcb-03fc25de23d9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>first_name</value>
         <variableId>18b23369-a1cb-4303-85aa-a6840f8666cc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>748738a8-3d43-4b52-bfcb-03fc25de23d9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>last_name</value>
         <variableId>3c6d7740-d1b2-459d-8f12-f386f31987fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>748738a8-3d43-4b52-bfcb-03fc25de23d9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>gender</value>
         <variableId>bc3aaab5-292e-4f6c-b744-a806c55d2a4d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>748738a8-3d43-4b52-bfcb-03fc25de23d9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>hire_date</value>
         <variableId>03a87b8e-ad86-4987-a191-55c52a81fcae</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>54ab322d-3e61-458c-9d1b-685377f92ab1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Connection in each test case/SC - Verify update is changing employee</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>66f838ef-d1ba-43df-8c9a-479bfe06a96e</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Connection in each test case/Verify update is changing employee</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>66f838ef-d1ba-43df-8c9a-479bfe06a96e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>empNo</value>
         <variableId>ea897b1d-e96d-477b-93bd-adbe6f0f92a5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>66f838ef-d1ba-43df-8c9a-479bfe06a96e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>newBirthDate</value>
         <variableId>b49ce0be-41c6-4d14-a05b-df905f2f22f4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c620a024-fca7-4410-b3c2-4be19fc74b60</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Connection in each test case/SC - Verify delete is removing employee</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>e3ec6d47-644d-43c3-a9f9-0f6a55f09585</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Connection in each test case/Verify delete is removing employee</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>e3ec6d47-644d-43c3-a9f9-0f6a55f09585</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>empNo</value>
         <variableId>30736491-324b-4b21-a861-1075d45e21aa</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
